/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    instructors: InstructorAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    instructors: Instructor;
    assignments: Assignment;
    submissions: Submission;
    announcements: Announcement;
    enrollments: Enrollment;
    'course-progress': CourseProgress;
    certificates: Certificate;
    courses: Course;
    testimonials: Testimonial;
    categories: Category;
    packages: Package;
    'udemy-courses': UdemyCourse;
    'admin-activity': AdminActivity;
    'media-assets': MediaAsset;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    instructors: InstructorsSelect<false> | InstructorsSelect<true>;
    assignments: AssignmentsSelect<false> | AssignmentsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    'course-progress': CourseProgressSelect<false> | CourseProgressSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    'udemy-courses': UdemyCoursesSelect<false> | UdemyCoursesSelect<true>;
    'admin-activity': AdminActivitySelect<false> | AdminActivitySelect<true>;
    'media-assets': MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-config': SiteConfig;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Instructor;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface InstructorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'instructor' | 'student' | 'staff') | null;
  status?: ('active' | 'pending' | 'suspended') | null;
  emailVerified?: boolean | null;
  phone?: string | null;
  /**
   * Optional avatar URL or initials image link
   */
  avatar?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors".
 */
export interface Instructor {
  id: number;
  name?: string | null;
  status?: ('active' | 'pending' | 'suspended') | null;
  emailVerified?: boolean | null;
  bio?: string | null;
  /**
   * Comma-separated e.g. Data Analytics, Python, SQL
   */
  expertise?: string | null;
  /**
   * Avatar image URL (leave blank to use initials)
   */
  photo?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  github?: string | null;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'instructors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments".
 */
export interface Assignment {
  id: number;
  course: number | Course;
  title: string;
  description?: string | null;
  dueDate?: string | null;
  maxPoints?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  instructor?: (number | null) | Instructor;
  category: number | Category;
  tag?: ('BOOTCAMP' | 'NEW' | 'POPULAR' | 'ADVANCED' | 'LIVE') | null;
  tagHot?: boolean | null;
  code?: string | null;
  title: string;
  desc?: string | null;
  duration?: string | null;
  lessons?: number | null;
  level?: ('Beginner' | 'Intermediate' | 'Advanced' | 'All levels') | null;
  price?: string | null;
  priceKobo?: number | null;
  old?: string | null;
  thumbnail?: string | null;
  format?: string | null;
  certificate?: string | null;
  guarantee?: string | null;
  support?: string | null;
  whatYouLearn?:
    | {
        benefit?: string | null;
        id?: string | null;
      }[]
    | null;
  programOverview?:
    | {
        week?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  courseContent?:
    | {
        title: string;
        duration?: string | null;
        summary?: string | null;
        content?: string | null;
        videoUrls?:
          | {
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        resources?:
          | {
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  whoThisIsFor?:
    | {
        audience?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedCourses?: (number | Course)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  n?: string | null;
  title: string;
  desc?: string | null;
  count?: string | null;
  /**
   * Optional thumbnail image URL for category cards
   */
  thumbnail?: string | null;
  icon?:
    | (
        | 'Cpu'
        | 'BarChart'
        | 'GitBranch'
        | 'Megaphone'
        | 'Code'
        | 'Puzzle'
        | 'Users'
        | 'Target'
        | 'Zap'
        | 'Briefcase'
        | 'Building'
        | 'ShoppingBag'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  assignment: number | Assignment;
  studentEmail: string;
  content?: string | null;
  status?: ('submitted' | 'graded' | 'returned') | null;
  grade?: number | null;
  feedback?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  course: number | Course;
  title: string;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  student: number | User;
  course: number | Course;
  status?: ('pending' | 'paid') | null;
  amount?: number | null;
  reference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress".
 */
export interface CourseProgress {
  id: number;
  student: number | User;
  course: number | Course;
  lastOpenedLessonIndex?: number | null;
  completedLessonIndexes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  student: number | User;
  course: number | Course;
  instructor: number | Instructor;
  issuedAt: string;
  certificateCode: string;
  studentName?: string | null;
  studentEmail?: string | null;
  courseTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  initials?: string | null;
  quote: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  icon?: ('Briefcase' | 'User' | 'Building' | 'ShoppingBag' | 'Zap' | 'Target' | 'Users' | 'Crown' | 'Star') | null;
  featured?: boolean | null;
  badge?: string | null;
  name: string;
  desc?: string | null;
  price?: string | null;
  per?: string | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "udemy-courses".
 */
export interface UdemyCourse {
  id: number;
  title: string;
  author?: string | null;
  rating?: number | null;
  count?: string | null;
  hours?: string | null;
  price?: string | null;
  /**
   * Full Udemy course URL (e.g. https://www.udemy.com/course/...)
   */
  udemyUrl?: string | null;
  /**
   * Upload from your computer to S3, or paste the Udemy preview image URL
   */
  thumbnail?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-activity".
 */
export interface AdminActivity {
  id: number;
  actor: string;
  action: 'created' | 'updated' | 'deleted' | 'status-changed' | 'password-reset' | 'bulk-suspend' | 'bulk-activate';
  targetCollection: string;
  targetId: string;
  targetLabel: string;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets".
 */
export interface MediaAsset {
  id: number;
  name: string;
  url: string;
  key?: string | null;
  bucket?: string | null;
  folder?: string | null;
  mimeType?: string | null;
  size?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'instructors';
        value: number | Instructor;
      } | null)
    | ({
        relationTo: 'assignments';
        value: number | Assignment;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'course-progress';
        value: number | CourseProgress;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'udemy-courses';
        value: number | UdemyCourse;
      } | null)
    | ({
        relationTo: 'admin-activity';
        value: number | AdminActivity;
      } | null)
    | ({
        relationTo: 'media-assets';
        value: number | MediaAsset;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'instructors';
        value: number | Instructor;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'instructors';
        value: number | Instructor;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  emailVerified?: T;
  phone?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors_select".
 */
export interface InstructorsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  emailVerified?: T;
  bio?: T;
  expertise?: T;
  photo?: T;
  linkedin?: T;
  twitter?: T;
  github?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assignments_select".
 */
export interface AssignmentsSelect<T extends boolean = true> {
  course?: T;
  title?: T;
  description?: T;
  dueDate?: T;
  maxPoints?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  assignment?: T;
  studentEmail?: T;
  content?: T;
  status?: T;
  grade?: T;
  feedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  course?: T;
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  student?: T;
  course?: T;
  status?: T;
  amount?: T;
  reference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress_select".
 */
export interface CourseProgressSelect<T extends boolean = true> {
  student?: T;
  course?: T;
  lastOpenedLessonIndex?: T;
  completedLessonIndexes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  student?: T;
  course?: T;
  instructor?: T;
  issuedAt?: T;
  certificateCode?: T;
  studentName?: T;
  studentEmail?: T;
  courseTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  instructor?: T;
  category?: T;
  tag?: T;
  tagHot?: T;
  code?: T;
  title?: T;
  desc?: T;
  duration?: T;
  lessons?: T;
  level?: T;
  price?: T;
  priceKobo?: T;
  old?: T;
  thumbnail?: T;
  format?: T;
  certificate?: T;
  guarantee?: T;
  support?: T;
  whatYouLearn?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  programOverview?:
    | T
    | {
        week?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  courseContent?:
    | T
    | {
        title?: T;
        duration?: T;
        summary?: T;
        content?: T;
        videoUrls?:
          | T
          | {
              url?: T;
              id?: T;
            };
        resources?:
          | T
          | {
              url?: T;
              id?: T;
            };
        id?: T;
      };
  whoThisIsFor?:
    | T
    | {
        audience?: T;
        id?: T;
      };
  relatedCourses?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  initials?: T;
  quote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  n?: T;
  title?: T;
  desc?: T;
  count?: T;
  thumbnail?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  icon?: T;
  featured?: T;
  badge?: T;
  name?: T;
  desc?: T;
  price?: T;
  per?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "udemy-courses_select".
 */
export interface UdemyCoursesSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  rating?: T;
  count?: T;
  hours?: T;
  price?: T;
  udemyUrl?: T;
  thumbnail?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-activity_select".
 */
export interface AdminActivitySelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  targetCollection?: T;
  targetId?: T;
  targetLabel?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  key?: T;
  bucket?: T;
  folder?: T;
  mimeType?: T;
  size?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  topbarLocation?: string | null;
  topbarAnnouncement?: string | null;
  topbarPhoneLabel?: string | null;
  topbarPhoneHref?: string | null;
  topbarSupportLabel?: string | null;
  topbarSupportHref?: string | null;
  topbarPartnersLabel?: string | null;
  topbarPartnersHref?: string | null;
  headerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  heroBadge?: string | null;
  heroHeadline?: string | null;
  heroLede?: string | null;
  /**
   * e.g. 12,400+
   */
  statLearners?: string | null;
  /**
   * e.g. 125+
   */
  statCourses?: string | null;
  /**
   * e.g. 12
   */
  statCareerTracks?: string | null;
  statPlacement?: string | null;
  statRating?: string | null;
  trustedLabel?: string | null;
  trustedCompanies?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredCoursesEyebrow?: string | null;
  featuredCoursesHeadline?: string | null;
  featuredCoursesBody?: string | null;
  udemyEyebrow?: string | null;
  udemyHeadline?: string | null;
  udemyBody?: string | null;
  whyUsEyebrow?: string | null;
  whyUsHeadline?: string | null;
  whyUsBody?: string | null;
  categoriesEyebrow?: string | null;
  categoriesHeadline?: string | null;
  categoriesBody?: string | null;
  packagesEyebrow?: string | null;
  packagesHeadline?: string | null;
  packagesBody?: string | null;
  testimonialsEyebrow?: string | null;
  testimonialsHeadline?: string | null;
  testimonialsBody?: string | null;
  footerHeadline?: string | null;
  footerAddress?: string | null;
  footerEmail?: string | null;
  footerPhone?: string | null;
  footerLearnTitle?: string | null;
  footerLearnLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerBusinessTitle?: string | null;
  footerBusinessLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerResourcesTitle?: string | null;
  footerResourcesLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerSocialLinks?:
    | {
        platform: 'Facebook' | 'X' | 'Instagram' | 'LinkedIn' | 'YouTube';
        href: string;
        id?: string | null;
      }[]
    | null;
  footerNewsletterTitle?: string | null;
  footerNewsletterBody?: string | null;
  footerNewsletterPlaceholder?: string | null;
  footerNewsletterButton?: string | null;
  footerNewsletterNote?: string | null;
  footerCopyright?: string | null;
  footerLegalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  finalCtaEyebrow?: string | null;
  finalCtaSecondaryLabel?: string | null;
  finalCtaSecondaryHref?: string | null;
  ctaHeadline?: string | null;
  ctaBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  topbarLocation?: T;
  topbarAnnouncement?: T;
  topbarPhoneLabel?: T;
  topbarPhoneHref?: T;
  topbarSupportLabel?: T;
  topbarSupportHref?: T;
  topbarPartnersLabel?: T;
  topbarPartnersHref?: T;
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  heroBadge?: T;
  heroHeadline?: T;
  heroLede?: T;
  statLearners?: T;
  statCourses?: T;
  statCareerTracks?: T;
  statPlacement?: T;
  statRating?: T;
  trustedLabel?: T;
  trustedCompanies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  featuredCoursesEyebrow?: T;
  featuredCoursesHeadline?: T;
  featuredCoursesBody?: T;
  udemyEyebrow?: T;
  udemyHeadline?: T;
  udemyBody?: T;
  whyUsEyebrow?: T;
  whyUsHeadline?: T;
  whyUsBody?: T;
  categoriesEyebrow?: T;
  categoriesHeadline?: T;
  categoriesBody?: T;
  packagesEyebrow?: T;
  packagesHeadline?: T;
  packagesBody?: T;
  testimonialsEyebrow?: T;
  testimonialsHeadline?: T;
  testimonialsBody?: T;
  footerHeadline?: T;
  footerAddress?: T;
  footerEmail?: T;
  footerPhone?: T;
  footerLearnTitle?: T;
  footerLearnLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerBusinessTitle?: T;
  footerBusinessLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerResourcesTitle?: T;
  footerResourcesLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerSocialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  footerNewsletterTitle?: T;
  footerNewsletterBody?: T;
  footerNewsletterPlaceholder?: T;
  footerNewsletterButton?: T;
  footerNewsletterNote?: T;
  footerCopyright?: T;
  footerLegalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  finalCtaEyebrow?: T;
  finalCtaSecondaryLabel?: T;
  finalCtaSecondaryHref?: T;
  ctaHeadline?: T;
  ctaBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}